parameters:
    sam_monitoring_manager.class: CanalTP\SamMonitoringBundle\Service\Manager
    sam.service_monitoring.database.psql.class: CanalTP\SamMonitoringComponent\Service\Database\Psql
    sam.service_monitoring.http.rest.class: CanalTP\SamMonitoringComponent\Service\Http\Rest
    
services:
    sam_monitoring_manager:
        class: %sam_monitoring_manager.class%
        arguments: [@service_container]
